### PR TITLE
dump files for licenses and providers_licenses

### PR DESCRIPTION
**Pull request by majesticio**
@caparker I just want to make sure these dump files make sense to you. Let me know if I should change anything.

### CODE REVIEW

**Comment by russbiggs** [comment]
Using a `COPY` statement for this seems really difficult to maintain and read. When it comes time to add a new license the task of adding a new row would be tedious and prone to error. 

An `INSERT` statement would be a cleaner way to do this in my opinion.

```sql
INSERT INTO licenses (licenses_id, name)
VALUES
    (1, 'CC BY-SA 4.0'),
    (2, 'CC BY 2.5'),
    (3, 'CC0 1.0 DEED')
```

I also think the `providers_licenses.sql` may not be necessary. Since its depends on the providers table being load and those IDs may not be consistent across builds. @caparker may have other thoughts or insights.

**Comment by majesticio** [comment]
I believe that `COPY` is faster at importing data in bulk as it is optimized for this. It may be "safer" as well, because if any of the transactions fail nothing is imported. For this reason `IMPORT INTO` is more flexible. I am open to either, and will update accordingly once we decide what to use

**Comment by russbiggs** [comment]
Given this table is only ~10 rows performance isnt really an issue. Reviewing the other lookups we generally use `INSERT` with the exception of one in `measurands.sql`. It woudl be good to be consistent with whatever we choose. In the `init.sh` where we actually run these commands we are wrapping in a transaction, so the safety of failed insertions will be handled there. https://github.com/openaq/openaq-db/blob/fdcb4adb9b98ba615338cbb4db0918535c7724d5/openaqdb/init.sh#L38. I'm thinking to create a convention we use `INSERT` when its a SQL script like this, and use the `COPY from stdin` when reading from a bulk file. e.g. 

https://github.com/openaq/openaq-db/blob/fdcb4adb9b98ba615338cbb4db0918535c7724d5/openaqdb/init.sh#L40-L41


@caparker any thoughts?

**Comment by caparker** [comment]
Sorry, I am working on checking that it builds. But yes, performance is not an issue in this case and a transaction can be used in either method. So readability and maintainability is the most important to me. 

As for the format, I would use inserts for something this small and format them in such a way that its easy to read and maintain, ie, git can track row changes. 

As for the provider licenses, we do actually load a list of providers so for now lets just keep that

I question using the first measurements as the start date though. I think thats a false level of precision that could later make us think that date was a real start date. Especially if we load older data and then someone looks at those licenses and thinks we need to find an older one.  I would just set them at infinity and -infinity if possible. How do folks feel about that?

I may have more comments after I check the build so hold off on fixing anything

**Comment by caparker** [comment]
I updated the local install to, hopefully, make it easier to test new scripts and builds to the db and I merged it into this feature branch. If you want to test it out you should be able to pull this branch down and use `docker compose` to build the stack. I hardcoded an IP address for the dev stack and I renamed the db for the local build to `openaqdev`. 

It builds and installs fast so if you can take a second and test it out before I merge that would be great. Instructions are in the readme but it should be as simple as 

```
# from the root
docker compose up --build
# if you need to fix something you can do 
docker compose down  # required for me
docker compose up --build
```

**Pull request merged**
