### PR TITLE
update countries data and countries processing script

### PR DESCRIPTION
**Pull request by russbiggs**
Adds a new field, ISO_A3 to the countries table, and replaces the data loaded into the countries table (countries.csv.gz) to include geometries with higher fidelity.

Also includes a bash script to aid in downloading and processing the Natural Earth Admin 0 data used in the countries table.

### CODE REVIEW

**Comment by caparker** [comment]
@russbiggs 
Looks pretty good. I updated the order of the import so that the name and iso field were being populated correctly. And I wanted to check with you to make sure these all seem right. These are all the -99 codes. Norway and France jumped out at me.
```
  iso  | iso_a3 |                 name                 
-------+--------+--------------------------------------
 -99   | -99    | Norway
 -99   | -99    | Scarborough Reef
 -99   | -99    | Cyprus U.N. Buffer Zone
 -99   | -99    | Siachen Glacier
 -99   | -99    | Serranilla Bank
 -99   | -99    | Somaliland
 -99   | -99    | Dhekelia
 -99   | -99    | Baikonur Cosmodrome
 -99   | -99    | Bajo Nuevo Bank (Petrel Islands)
 -99   | -99    | France
 -99   | -99    | Kosovo
 -99   | -99    | Northern Cyprus
 -99   | -99    | Ashmore and Cartier Islands
 -99   | -99    | Clipperton Island
 -99   | -99    | Akrotiri
 -99   | -99    | Southern Patagonian Ice Field
 -99   | -99    | Bir Tawil
 -99   | -99    | Indian Ocean Territories
 -99   | -99    | Spratly Islands
 -99   | -99    | Coral Sea Islands
 -99   | -99    | Brazilian Island
 -99   | -99    | US Naval Base Guantanamo Bay
```

**Comment by caparker** [comment]
Also, we should consider geography instead of geometry to match the timezones

**Comment by russbiggs** [comment]
The -99 are likely due to this https://github.com/nvkelso/natural-earth-vector/issues/268#issuecomment-778832542. I'll update to use the "eh" column instead. 
I'll also update PR with geography in place of geometry

**Comment by caparker** [comment]
Looks good. I checked the new geography type against or current function and that seems good
```
openaqdev=# SELECT country(ST_MakePoint(-71.1043443253471, 42.3150676015829));
 country 
---------
 US
(1 row)
```
And I checked for duplicates in the ISO codes, that brought up these
```
openaqdev=# SELECT iso, iso_a3, name FROM countries WHERE iso IN (SELECT iso FROM countries WHERE iso != '-99' GROUP BY 1 HAVING COUNT(1)>1) ORDER BY 1;
 iso | iso_a3 |            name             
-----+--------+-----------------------------
 AU  | AUS    | Australia
 AU  | AUS    | Indian Ocean Territories
 AU  | AUS    | Ashmore and Cartier Islands
 AU  | AUS    | Coral Sea Islands
 BR  | BRA    | Brazilian Island
 BR  | BRA    | Brazil
 FR  | FRA    | France
 FR  | FRA    | Clipperton Island
 KZ  | KAZ    | Baikonur Cosmodrome
 KZ  | KAZ    | Kazakhstan
(10 rows)
```
Which seem to be fine but you are more familiar so I just wanted to point them out to you.

**Comment by russbiggs** [comment]
Duplicate ISO codes are fine, handles things like oversea territories, enclaves, exclaves etc.

**Pull request merged**
